# Pedagogía de la liberación
## Diseño libre en la educación
Esta discusión sobre Diseño libre surgió en el contexto de las actividades pedagógicas del Instituto Faber-Ludens y se volvió más estructurada durante la elaboración del programa de Educación a Distancia (EaD). La propuesta fue usar el Diseño Libre como una pedagogía.
Tres puntos fueron considerados como fundamentales:
1. Desarrollo de la autonomía del estudiante
2. Interacción con otros estudiantes
3. Desarrollo de las capacidades y habilidades de la estudiante a través del contacto con nuevas herramientas de trabajo.
La autonomía parte de la idea de que la estudiante sea más activa en relación con la enseñanza-aprendizaje. Se trata del inicio de la transición del modelo “bancario” de transferencia de conocimiento por parte de la profesora al alumno (modelo vertical) al modelo dialéctico, que permite una ganancia mutua entre alumno-profesora, porque cuando hay intercambio las dos partes salen ganando.
La validez del aprendizaje es intrínseca al ser humano, pues fue aprendiendo a lidiar con las intemperies del medio ambiente, a protegerse, a crear herramientas, y así con lo aprehendido el individuo descubrió que puede enseñar, es decir, compartir con los demás sus experiencias, así como la sociedad compartía entre sí también sus conocimientos.
Siguiendo este modelo la alumna se transforma en un sujeto activo y crítica con lo que existe en su entorno, contribuyendo a la construcción del conocimiento en todo momento; pasando a obtener la autonomía en el proceso enseñanza, con todo respeto a la profesora, quien ahora tiene un papel más de mediador del conocimiento, dialogando y puliendo ideas.^[Juliana, profesora del Centro Cultural de Brasil en El Salvador y traductora de este capítulo, emite en voz alta un ¡qué bonito! después de la traducción de este párrafo, imaginamos que se agencia del contenido aplicándolo a su propia experiencia pedagógica.]
## La profesora
El trabajo de las profesoras también es el de estimular a la alumna a desarrollar sus capacidades comunicativas, creando su propia visión del mundo, y manteniendo una buena relación con el grupo de compañeros que será reaprovechada también en las situaciones de trabajo donde la creatividad expresada a través del diálogo surge como una manera incisiva para resolver conflictos. Como dice Paulo Freire: “Lo que los profesores necesitan hacer es ayudar al alumno a reconocerse como arquitecto de su propio aprendizaje”.
Hasta la maduración de la idea de la Pedagogía del Diseño Libre, hubo un periodo con varios cuestionamientos con el fin de asegurar la misma calidad de aprendizaje de los cursos presenciales. El foco de la Pedagogía del Diseño Libre está en la cuestión de la calidad del aprendizaje y en la calidad de la enseñanza. Con este enfoque en el aprendizaje colaborativo, el desafío de la educación online es menor, debido a la capacidad del ser humano de relacionarse a pesar de la distancia física.
En la Pedagogía del Diseño Libre, el orden de aprendizaje es un orden sugerido. Es decir, la alumna puede formular su curva de aprendizaje conforme a su necesidad. El aprendizaje no es lineal. Por tanto, la alumna no queda presa en un flujo de actividades predeterminadas como se puede percibir en muchos cursos de EaD, en los cuáles es necesario terminar una etapa para obtener acceso al contenido de la siguiente etapa.
´
Además de la forma de evaluación del trabajo, que consiste en el envío de trabajos para la retroalimentación por parte de la profesora, permitiendo que la alumna rehaga o cuestione puntos del trabajo. En este abordaje pedagógico la alumna es la que observa su propio desarrollo, a través de la autoevaluación. El objetivo de la autoevaluación no es el de preguntar cosas que la alumna no sabe, y sí lo que ella sabe, así ella misma puede gestionar su aprendizaje.
## La movilidad
La movilidad también es un punto importante para la Pedagogía del Diseño Libre, pues la alumna necesita tener la libertad del contenido y adaptarse a su disponibilidad de tiempo, y no al contrario. Para esto los materiales multimedia son editados en formatos digitales que pueden ser utilizados en los dispositivos móviles actuales, dando a la alumna la libertad de aprender desde donde esté, y de aprovechar los pequeños recesos del día a día con este fin.
En el proyecto final del curso se realiza un trabajo grupal, en el cual es muy importante la buena relación entre las alumnas para que estas consigan crecer como conjunto, y no solamente con la relación vertical profesora-alumna. Esta interacción entre las alumnas es esencial para crear una especie de relación similar al pasillo del aula, presente en cursos con encuentros físicos. La creación de un espacio donde las alumnas puedan compararse y compartir conocimiento sin la mediación de la profesora. Para la realización de ese trabajo final se propuso a las alumnas la utilización de la plataforma Corais.
El equiparamiento de la alumna en la educación, no siendo simplemente una oyente, sino participando activamente de la construcción del conocimiento es la ruptura que estamos proponiendo en el modelo de EaD de la Pedagogía del Diseño Libre, independientemente de la tecnología utilizada.
El modelo de educación a distancia en sí ya es un desafío, el de superar las barreras geográficas y conseguir crear lazos de cooperación entre alumnas y profesoras. La utilización de la tecnología aplicada a la educación necesita de una filosofía de aprendizaje que garantice a las estudiantes una efectiva interacción con las colegas, dando oportunidad para el desarrollo de proyectos colaborativos independientemente de los aspectos culturales de cada individuo y estimulando la construcción de un conocimiento libre. El objetivo de la Pedagogía de Diseño Libre es el de proponer un modelo de educación más horizontal, de trueque de experiencias. La iniciativa de que el conocimiento sea construido de forma colaborativa, con la autonomía de que el alumno pueda realizar sus actividades con mayor libertad, pero aun así manteniendo la presencia de la profesora con una permanencia mayor que en los cursos presenciales.
La estudiante se transforma en la responsable de su propio aprendizaje. Puede decidir en qué áreas del curso va a querer profundizar y las que apenas mirará por encima. No es necesario que la profesora exija a la alumna que siga el currículo propuesto por obligación, pero sí alentar a esta alumna en su búsqueda del conocimiento.
> Los que pasan no saben
que ya somos eternos.
Con sólo tener esta
conciencia del misterio.
[David Escobar Galindo]